var play = {
  "midsummer": "A Midsummer Night's Dream",
  "allswell": "All's Well that Ends Well",
  "antcleo": "Antony and Cleopatra",
  "ayli": "As You Like It",
  "corio": "Coriolanus",
  "cym": "Cymbeline",
  "ham": "Hamlet",
  "henry4p1": "Henry IV, Part 1",
  "henry5": "Henry V",
  "henry6p1": "Henry VI, Part 1",
  "henry6p2": "Henry VI, Part 2",
  "henry6p3": "Henry VI, Part 3",
  "henry8": "Henry VIII",
  "jc": "Julius Caesar",
  "kj": "King John",
  "kl": "King Lear",
  "lll": "Love's Labour's Lost",
  "mac": "Macbeth",
  "meas": "Measure for Measure",
  "muchado": "Much Ado about Nothing",
  "oth": "Othello",
  "peri": "Pericles",
  "rich2": "Richard II",
  "rich3": "Richard III",
  "randj": "Romeo and Juliet",
  "comerr": "The Comedy of Errors",
  "merch": "The Merchant of Venice",
  "merry": "The Merry Wives of Windsor",
  "taming": "The Taming of the Shrew",
  "tempest": "The Tempest",
  "winters": "The Winter's Tale",
  "timon": "Timon of Athens",
  "titus": "Titus Andronicus",
  "troilus": "Troilus and Cressida",
  "12night": "Twelfth Night",
  "2gentlemen": "Two Gentlemen of Verona",
}
