var abbrevsToPlays = {
  "midsummer": "A Midsummer Night's Dream",
  "allswell": "All's Well that Ends Well",
  "antcleo": "Antony and Cleopatra",
  "ayli": "As You Like It",
  "corio": "Coriolanus",
  "cym": "Cymbeline",
  "ham": "Hamlet",
  "henry4p1": "Henry IV, Part 1",
  "henry5": "Henry V",
  "henry6p1": "Henry VI, Part 1",
  "henry6p2": "Henry VI, Part 2",
  "henry6p3": "Henry VI, Part 3",
  "henry8": "Henry VIII",
  "jc": "Julius Caesar",
  "kj": "King John",
  "lear": "King Lear",
  "lll": "Love's Labour's Lost",
  "mac": "Macbeth",
  "meas": "Measure for Measure",
  "muchado": "Much Ado about Nothing",
  "oth": "Othello",
  "peri": "Pericles",
  "rich2": "Richard II",
  "rich3": "Richard III",
  "randj": "Romeo and Juliet",
  "comerr": "The Comedy of Errors",
  "merch": "The Merchant of Venice",
  "merry": "The Merry Wives of Windsor",
  "taming": "The Taming of the Shrew",
  "tempest": "The Tempest",
  "winters": "The Winter's Tale",
  "timon": "Timon of Athens",
  "titus": "Titus Andronicus",
  "troilus": "Troilus and Cressida",
  "12night": "Twelfth Night",
  "2gentlemen": "Two Gentlemen of Verona",
  "2noble": "Two Noble Kinsmen",
}

var playsToAbbrevs = {
  "A Midsummer Night's Dream": "midsummer",
  "All's Well that Ends Well": "allswell",
  "Antony and Cleopatra": "antcleo",
  "As You Like It": "ayli",
  "Coriolanus": "corio",
  "Cymbeline": "cym",
  "Hamlet": "ham",
  "Henry IV, Part 1": "henry4p1",
  "Henry V": "henry5",
  "Henry VI, Part 1": "henry6p1",
  "Henry VI, Part 2": "henry6p2",
  "Henry VI, Part 3": "henry6p3",
  "Henry VIII": "henry8",
  "Julius Caesar": "jc",
  "King John": "kj",
  "King Lear": "lear",
  "Love's Labour's Lost": "lll",
  "Macbeth": "mac",
  "Measure for Measure": "meas",
  "Much Ado about Nothing": "muchado",
  "Othello": "oth",
  "Pericles": "peri",
  "Richard II": "rich2",
  "Richard III": "rich3",
  "Romeo and Juliet": "randj",
  "The Comedy of Errors": "comerr",
  "The Merchant of Venice": "merch",
  "The Merry Wives of Windsor": "merry",
  "The Taming of the Shrew": "taming",
  "The Tempest": "tempest",
  "The Winter's Tale": "winters",
  "Timon of Athens": "timon",
  "Titus Andronicus": "titus",
  "Troilus and Cressida": "troilus",
  "Twelfth Night": "12night",
  "Two Gentlemen of Verona": "2gentlemen",
  "Two Noble Kinsmen": "2noble",
}
