var summaries = {
  "All’s Well that Ends Well": "Bertie runs away to avoid his new wife, Helena, but she follows him and tricks him into being her faithful husband.",
  "As You Like It": "A romp in the Forest of Arden, where everyone falls in love.",
  "The Comedy of Errors": "Two sets of twins turn the town of Ephesus upside down.",
  "Cymbeline": "A jealous husband believes a false story about his wife. She runs away and meets her long-lost brothers.",
  "Love’s Labour’s Lost": "The King of Navarre and his court try to study in seclusion but succumb to the temptations of love.",
  "Measure for Measure": "Power corrupts Angelo, the substitute duke, who tries to seduce the sister of a condemned man.",
  "The Merchant of Venice": "Moneylender Shylock tries to recover his “pound of flesh” collateral for a loan.",
  "The Merry Wives of Windsor": "Sir John Falstaff puts the moves on the Merry Wives, who turn the tables on him.",
  "A Midsummer Night’s Dream": "Mix-and-match couples in the woods near Athens. “Lord, what fools these mortals be!”",
  "Much Ado about Nothing": "Claudio loves Hero. Benedick doesn’t like Beatrice. Then Claudio hates Hero, and Benedick loves Beatrice. Eventually, everyone gets married.",
  "Pericles": "Pericles lives, loves, loses, and regains his family while touring the Mediterranean Sea.",
  "The Taming of the Shrew": "Petruchio “tames” his wife, Katherina.",
  "The Tempest": "Prospero uses magic to reclaim his dukedom and find a husband for his daughter, Miranda.",
  "Troilus and Cressida": "In ancient Troy, Troilus and Cressida vow undying love, which dies all too quickly.",
  "Twelfth Night": "Orsino loves Olivia. Olivia loves Cesario. Cesario is really Viola, who loves Orsino.",
  "Two Gentlemen of Verona": "Nothing can come between best friends Valentine and Proteus, except a girl, Sylvia.",
  "Two Noble Kinsmen": "Two brothers fight for love in ancient Greece.",
  "The Winter’s Tale": "Jealous husband Leontes drives away his wife, children, and best friend.",
  "King John": "John turns over England to the Pope.",
  "Richard II": "Henry Bolingbroke deposes King Richard and becomes King Henry IV.",
  "Henry IV, Part 1": "Henry wonders why his son can’t be more like that nice Hotspur boy, until Hotspur rebels against the king.",
  "Henry IV, Part 2": "Henry’s son Hal continues to act up, and rebels still threaten the throne, but Hal comes out all right in the end and becomes King Henry V.",
  "Henry V": "Henry invades France.",
  "Henry VI, Part 1": "Joan of Arc leads the French army against England. The Houses of York and Lancaster start a spat that lasts through the next three plays.",
  "Henry VI, Part 2": "Peasants and the House of York rebel against King Henry.",
  "Henry VI, Part 3": "The House of York deposes King Henry, despite help from France. Edward, son of the Duke of York, takes the throne as King Edward IV.",
  "Richard III": "Edward’s brother, Richard, kills everyone in his way and seizes the throne, only to lose it and his life.",
  "Henry VIII": "King Henry divorces his wife, starts a new church, remarries, and fathers a daughter who becomes Queen Elizabeth I.",
  "Antony and Cleopatra": "Antony tries to balance love and war but sacrifices everything for love.",
  "Coriolanus": "Rome’s best general feels slighted, so he switches sides.",
  "Hamlet": "A young prince plans revenge against his murdering uncle.",
  "Julius Caesar": "Brutus and others kill Caesar to prevent him from becoming king.",
  "King Lear": "Lear gives up his kingdom to his daughters and then gives up his mind.",
  "Macbeth": "Witches’ prophecies prompt Macbeth to seize the throne of Scotland.",
  "Othello": "Iago preys on Othello’s jealousy and drives him to murder.",
  "Romeo and Juliet": "Forbidden love tempts and destroys a young couple.",
  "Timon of Athens": "Overgenerous Timon learns who his true friends are when he runs out of money.",
  "Titus Andronicus": "Bloody revenge in ancient Rome, with the emphasis on bloody."
}
